{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "x-ibm-name": "cbs-info-api-10",
    "title": "CBS Info API",
    "description": "Şehirler,ilçeler mahalleler gibi coğrafik bilgileri getirir ve servis dışı ve mobil olan alanları listeler.|Gets geographic informations like citites, districts, neighborhoods and lists out of service areas and mobile areas.",
    "termsOfService": "http://swagger.io/terms/"
  },
  "basePath": "/mngapi/api/cbsinfoapi",
  "paths": {
    "/getcities": {
      "get": {
        "tags": [
          "CBSInfo"
        ],
        "summary": "Get Cities",
        "description": "Türkiye'deki şehirlerin ismini ve kodlarını getirir. | Gets city names and city codes of Turkey.",
        "operationId": "GetcitiesGet",
        "consumes": [],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "x-api-version",
            "in": "header",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "uniqueItems": false,
              "type": "array",
              "items": {
                "$ref": "#/definitions/GetCitiesResponse"
              }
            },
            "examples": {
              "application/json": [
                {
                  "code": "01",
                  "name": "Adana"
                },
                {
                  "code": "02",
                  "name": "Adıyaman"
                }
              ]
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Cities not found",
            "schema": {
              "$ref": "#/definitions/ProblemDetails"
            }
          },
          "500": {
            "description": "Server Error"
          }
        }
      }
    },
    "/getdistricts/{cityCode}": {
      "get": {
        "tags": [
          "CBSInfo"
        ],
        "summary": "Get Districts By City Code",
        "description": "İlgili şehir koduna ait ilçe isimlerini ve kodlarını getirir. | Gets district names and district codes of the relevant city code.",
        "operationId": "GetdistrictsByCityCodeGet",
        "consumes": [],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "cityCode",
            "in": "path",
            "description": "gets districts according to given cityCode",
            "required": true,
            "type": "string"
          },
          {
            "name": "x-api-version",
            "in": "header",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "uniqueItems": false,
              "type": "array",
              "items": {
                "$ref": "#/definitions/GetDistrictsResponse"
              }
            },
            "examples": {
              "application/json": [
                {
                  "cityCode": "01",
                  "cityName": "Adana",
                  "code": "85",
                  "name": "Çukurova"
                },
                {
                  "cityCode": "01",
                  "cityName": "Adana",
                  "code": "86",
                  "name": "Sarıçam"
                }
              ]
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "District not found",
            "schema": {
              "$ref": "#/definitions/ProblemDetails"
            }
          },
          "500": {
            "description": "Server Error"
          }
        }
      }
    },
    "/getneighborhoods/{cityCode}/{districtCode}": {
      "get": {
        "tags": [
          "CBSInfo"
        ],
        "summary": "Get Neighborhoods By City Code and District Code",
        "description": "İlgili şehir ve ilçe koduna ait mahallelerin bilgisini getirir. | Gets neighborhoods informations of the relevant city code and district code.",
        "operationId": "GetneighborhoodsByCityCodeByDistrictCodeGet",
        "consumes": [],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "cityCode",
            "in": "path",
            "description": "gets out of service area according to given cityCode",
            "required": true,
            "type": "string"
          },
          {
            "name": "districtCode",
            "in": "path",
            "description": "gets out of service area according to given districtCode",
            "required": true,
            "type": "string"
          },
          {
            "name": "x-api-version",
            "in": "header",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "uniqueItems": false,
              "type": "array",
              "items": {
                "$ref": "#/definitions/GetNeighborhoodResponse"
              }
            },
            "examples": {
              "application/json": [
                {
                  "cityId": "34",
                  "disctrictId": "56",
                  "distirict": "Gaziosmanpşa",
                  "neighborhood": "Çeliktepe Mahallesi"
                },
                {
                  "cityId": "34",
                  "disctrictId": "56",
                  "distirict": "Gaziosmanpşa",
                  "neighborhood": "Pınar Mahallesi"
                }
              ]
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Neighborhood not found",
            "schema": {
              "$ref": "#/definitions/ProblemDetails"
            }
          },
          "500": {
            "description": "Server Error"
          }
        }
      }
    },
    "/getoutofserviceareas/{cityCode}/{districtCode}": {
      "get": {
        "tags": [
          "CBSInfo"
        ],
        "summary": "Get Get Out Of Service Areas By City Code and District Code",
        "description": "İlgili şehir ve ilçe koduna ait servis dışı olan mahallelerin bilgisini getirir. | Gets out of service area informations of the relevant city code and district code.",
        "operationId": "GetoutofserviceareasByCityCodeByDistrictCodeGet",
        "consumes": [],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "cityCode",
            "in": "path",
            "description": "gets out of service area according to given cityCode",
            "required": true,
            "type": "string"
          },
          {
            "name": "districtCode",
            "in": "path",
            "description": "gets out of service area according to given districtCode",
            "required": true,
            "type": "string"
          },
          {
            "name": "x-api-version",
            "in": "header",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "uniqueItems": false,
              "type": "array",
              "items": {
                "$ref": "#/definitions/GetOutOfServiceAreaResponse"
              }
            },
            "examples": {
              "application/json": [
                {
                  "cityId": "34",
                  "disctrictId": "56",
                  "distirict": "Gaziosmanpşa",
                  "neighborhood": "Pınar Mahallesi"
                },
                {
                  "cityId": "34",
                  "disctrictId": "56",
                  "distirict": "Gaziosmanpşa",
                  "neighborhood": "Pınar Mahallesi"
                }
              ]
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Out of service area not found",
            "schema": {
              "$ref": "#/definitions/ProblemDetails"
            }
          },
          "500": {
            "description": "Server Error"
          }
        }
      }
    },
    "/getmobileareas/{cityCode}/{districtCode}": {
      "get": {
        "tags": [
          "CBSInfo"
        ],
        "summary": "Get Mobile Areas By City Code and District Code",
        "description": "İlgili şehir ve ilçe koduna ait mobil mahalle bilgisini getirir. | Gets mobil area informations of the relevant city code and district code.",
        "operationId": "GetmobileareasByCityCodeByDistrictCodeGet",
        "consumes": [],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "cityCode",
            "in": "path",
            "description": "gets mobile area according to given cityCode",
            "required": true,
            "type": "string"
          },
          {
            "name": "districtCode",
            "in": "path",
            "description": "gets mobile area according to given districtCode",
            "required": true,
            "type": "string"
          },
          {
            "name": "x-api-version",
            "in": "header",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "uniqueItems": false,
              "type": "array",
              "items": {
                "$ref": "#/definitions/GetMobileAreaResponse"
              }
            },
            "examples": {
              "application/json": [
                {
                  "cityId": "34",
                  "disctrictId": "56",
                  "distirict": "Gaziosmanpşa",
                  "neighborhood": "Çeliktepe Mahallesi"
                },
                {
                  "cityId": "34",
                  "disctrictId": "56",
                  "distirict": "Gaziosmanpşa",
                  "neighborhood": "Pınar Mahallesi"
                }
              ]
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Mobile area not found",
            "schema": {
              "$ref": "#/definitions/ProblemDetails"
            }
          },
          "500": {
            "description": "Server Error"
          }
        }
      }
    }
  },
  "definitions": {
    "GetCitiesResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "ProblemDetails": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "status": {
          "format": "int32",
          "type": "integer"
        },
        "detail": {
          "type": "string"
        },
        "instance": {
          "type": "string"
        }
      },
      "additionalProperties": {
        "type": "object"
      }
    },
    "GetDistrictsResponse": {
      "type": "object",
      "properties": {
        "cityCode": {
          "type": "string"
        },
        "cityName": {
          "type": "string"
        },
        "code": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "GetNeighborhoodResponse": {
      "type": "object",
      "properties": {
        "cityId": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "disctrictId": {
          "type": "string"
        },
        "distirict": {
          "type": "string"
        },
        "neighborhood": {
          "type": "string"
        }
      }
    },
    "GetOutOfServiceAreaResponse": {
      "type": "object",
      "properties": {
        "cityId": {
          "type": "string"
        },
        "disctrictId": {
          "type": "string"
        },
        "distirict": {
          "type": "string"
        },
        "neighborhood": {
          "type": "string"
        }
      }
    },
    "GetMobileAreaResponse": {
      "type": "object",
      "properties": {
        "cityId": {
          "type": "string"
        },
        "disctrictId": {
          "type": "string"
        },
        "distirict": {
          "type": "string"
        },
        "neighborhood": {
          "type": "string"
        }
      }
    }
  },
  "x-ibm-configuration": {
    "enforced": true,
    "testable": true,
    "phase": "realized",
    "cors": {
      "enabled": true
    },
    "type": "rest",
    "servers": [
      {
        "url": "https://api.mngkargo.com.tr/mngapi/api/cbsinfoapi",
        "type": [
          "development",
          "production"
        ]
      }
    ]
  },
  "securityDefinitions": {
    "api-key-1": {
      "description": "",
      "in": "header",
      "name": "X-IBM-Client-Id",
      "type": "apiKey"
    },
    "api-key-2": {
      "description": "",
      "in": "header",
      "name": "X-IBM-Client-Secret",
      "type": "apiKey"
    }
  },
  "security": [
    {
      "api-key-2": [],
      "api-key-1": []
    }
  ],
  "x-ibm-comment": [
    "AMU version used to port this API: v10.0.5.3-R1-680cbea6bb81861c86dc4522ed22fba48a697875-2023-05-09T21:45:55Z",
    "API06: Changed gateway type to `datapower-api-gateway`.",
    "API14: Ported v5-compatible policies to work with the API Gateway and updated policy versions.",
    "API45: Compatibility toggle: `allow-chunked-uploads` set to value: `false`, which is the same as the API Gateway default. For details, see: https://www.ibm.com/docs/en/api-connect/10.0.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#COMPAT_TOGGLE_MATCHES_APIGW_DEFAULT",
    "API45: Compatibility toggle: `copy-id-headers-to-message` set to value: `false`, which is the same as the API Gateway default. For details, see: https://www.ibm.com/docs/en/api-connect/10.0.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#COMPAT_TOGGLE_MATCHES_APIGW_DEFAULT",
    "API45: Compatibility toggle: `return-v5-responses` set to value: `false`, which is the same as the API Gateway default. For details, see: https://www.ibm.com/docs/en/api-connect/10.0.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#COMPAT_TOGGLE_MATCHES_APIGW_DEFAULT",
    "API61: Set buffering property to true. For details, see: https://www.ibm.com/docs/en/api-connect/10.0.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#SET_BUFFERING",
    "API24: Removed redundant `parse` policy from the beginning of the assembly. For details, see: https://www.ibm.com/docs/en/api-connect/10.0.x?topic=cadag-messages-generated-during-conversion-apis-datapower-api-gateway#REMOVED_REDUNDANT_FRONT_PARSE"
  ],
  "schemes": [
    "https"
  ],
  "host": "api.mngkargo.com.tr"
}